### ISSUE TITLE
sirv clears the screen at startup, overwriting log output from upstream tools

### ISSUE THREAD

**Issue by johndunderhill** [lukeed/sirv#81] opened 2020-09-06 09:35 UTC
I'm seeing this while using rollup in Svelte, and it's very annoying.  I think the rollup people still have an issue open about this, but it's sirv that's doing it (I have their flag set not to clear the screen).

Would you mind adding

```
.option('-n, --noclear', 'Do not clear the screen on startup', false)
```

to bin.js, and changing

```
if (opts.clear !== false) clear(true);
```

in index.js to something like

```
if (opts.clear !== false && opts.noclear !== true) clear(true);
```

opts.clear doesn't seem to be used, but just in case.  I could pass --quiet, but I love seeing that little rocket.  :)

**Comment by lukeed** [comment] 2020-09-06 15:37
Hey,

It's disabled via `--no-clear` - note the hyphen.

Closing as duplicate of #58 but please let me know if that resolved for you. Thanks!

**Closed by lukeed** 2020-09-06 15:37 UTC

**Comment by johndunderhill** [comment] 2020-09-06 20:58
Thank you, works.  You might want to add this to the doc.
